{
 "title": "Cyberpower PDU",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": "label_values(ePDUIdentName,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load - Amps",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.1*ePDULoadStatusLoad{instance=\"$instance\",ePDULoadStatusIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Load - Volts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    {
     "expr": "ePDULoadStatusApparentPower{instance=\"$instance\", ePDULoadStatusIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Load - Watts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "ePDULoadStatusActivePower{instance=\"$instance\", ePDULoadStatusIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.1*0.1*ePDULoadStatusPowerFactor{instance=\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "Total Energy Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.1*ePDULoadStatusEnergy{instance=\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg(0.1*ePDUStatusInputVoltage{instance=\"$instance\"})",
     "legendFormat": "Input"
    }
   ]
  },
  {
   "title": "Outlet Load - Amps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "0.1*ePDUOutletStatusLoad{instance=\"$instance\"}",
     "legendFormat": "Outlet {{ePDUOutletStatusIndex}}"
    }
   ]
  }
 ]
}